spring:
  config:
    import:
      optional:file:.env[.properties]
  application:
    name:
      backend
  datasource:
    url:
      jdbc:postgresql://${DATABASE_HOST}/${DATABASE}
    driver-class-name:
      org.postgresql.Driver
    username:
      ${DATABASE_USER}
    password:
      ${DATABASE_PASSWORD}
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db/migration
    enabled: false
server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/v1

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
casbin:
  store-type: jdbc
  table-name: casbin_rule
  initialize-schema: create

