spring:
   application:
      name:
         backend
   datasource:
      url:
         http://localhost:5432
      driver-class-name:
         org.postgresql.Driver
      username:
         postgres
      password:
         password
   data:
      jdbc:
         dialect: postgresql


server:
   port: 8080